import type { Catalog, Ingredient, Recipe } from './types.ts';

/** timestamp เดียวกันทั้งชุด — ใช้เป็นค่า updatedAt ตั้งต้นของคลัง */
export const SEED_UPDATED_AT = '2026-07-04T00:00:00.000Z';

export const seedIngredients: Ingredient[] = [
  // โปรตีน
  { id: 'chicken', name: 'ไก่', group: 'protein', sortOrder: 0 },
  { id: 'pork', name: 'หมู', group: 'protein', sortOrder: 1 },
  { id: 'pork-minced', name: 'หมูสับ', group: 'protein', sortOrder: 2 },
  { id: 'shrimp', name: 'กุ้ง', group: 'protein', sortOrder: 3 },
  { id: 'egg', name: 'ไข่', group: 'protein', sortOrder: 4 },
  { id: 'beef', name: 'เนื้อวัว', group: 'protein', sortOrder: 5 },
  { id: 'fish', name: 'ปลา', group: 'protein', sortOrder: 6 },
  { id: 'squid', name: 'ปลาหมึก', group: 'protein', sortOrder: 7 },
  { id: 'tofu', name: 'เต้าหู้', group: 'protein', sortOrder: 8 },
  { id: 'crispy-pork', name: 'หมูกรอบ', group: 'protein', sortOrder: 9 },
  { id: 'canned-fish', name: 'ปลากระป๋อง', group: 'protein', sortOrder: 10 },
  { id: 'clam', name: 'หอยลาย', group: 'protein', sortOrder: 11 },
  { id: 'crab-meat', name: 'เนื้อปู', group: 'protein', sortOrder: 12 },
  { id: 'mackerel', name: 'ปลาทู', group: 'protein', sortOrder: 13 },
  // ผักและสมุนไพร
  { id: 'holy-basil', name: 'ใบกะเพรา', group: 'vegetable', sortOrder: 0 },
  { id: 'garlic', name: 'กระเทียม', group: 'vegetable', sortOrder: 1 },
  { id: 'chili', name: 'พริก', group: 'vegetable', sortOrder: 2 },
  { id: 'morning-glory', name: 'ผักบุ้ง', group: 'vegetable', sortOrder: 3 },
  { id: 'spring-onion', name: 'ต้นหอม', group: 'vegetable', sortOrder: 4 },
  { id: 'yardlong-bean', name: 'ถั่วฝักยาว', group: 'vegetable', sortOrder: 5 },
  { id: 'tomato', name: 'มะเขือเทศ', group: 'vegetable', sortOrder: 6 },
  { id: 'lemongrass', name: 'ตะไคร้', group: 'vegetable', sortOrder: 7 },
  { id: 'galangal', name: 'ข่า', group: 'vegetable', sortOrder: 8 },
  { id: 'kaffir-lime-leaf', name: 'ใบมะกรูด', group: 'vegetable', sortOrder: 9 },
  { id: 'mushroom', name: 'เห็ด', group: 'vegetable', sortOrder: 10 },
  { id: 'curry-paste', name: 'พริกแกง', group: 'vegetable', sortOrder: 11 },
  { id: 'thai-basil', name: 'โหระพา', group: 'vegetable', sortOrder: 12 },
  { id: 'chinese-kale', name: 'คะน้า', group: 'vegetable', sortOrder: 13 },
  { id: 'cabbage', name: 'กะหล่ำปลี', group: 'vegetable', sortOrder: 14 },
  { id: 'napa-cabbage', name: 'ผักกาดขาว', group: 'vegetable', sortOrder: 15 },
  { id: 'bean-sprout', name: 'ถั่วงอก', group: 'vegetable', sortOrder: 16 },
  { id: 'onion', name: 'หอมใหญ่', group: 'vegetable', sortOrder: 17 },
  { id: 'shallot', name: 'หอมแดง', group: 'vegetable', sortOrder: 18 },
  { id: 'ginger', name: 'ขิง', group: 'vegetable', sortOrder: 19 },
  { id: 'carrot', name: 'แครอท', group: 'vegetable', sortOrder: 20 },
  { id: 'baby-corn', name: 'ข้าวโพดอ่อน', group: 'vegetable', sortOrder: 21 },
  { id: 'thai-eggplant', name: 'มะเขือเปราะ', group: 'vegetable', sortOrder: 22 },
  { id: 'green-papaya', name: 'มะละกอดิบ', group: 'vegetable', sortOrder: 23 },
  { id: 'pumpkin', name: 'ฟักทอง', group: 'vegetable', sortOrder: 24 },
  { id: 'sponge-gourd', name: 'บวบ', group: 'vegetable', sortOrder: 25 },
  { id: 'choy-sum', name: 'ผักกวางตุ้ง', group: 'vegetable', sortOrder: 26 },
  { id: 'cucumber', name: 'แตงกวา', group: 'vegetable', sortOrder: 27 },
  // คาร์โบไฮเดรต
  { id: 'cooked-rice', name: 'ข้าวสวย', group: 'carb', sortOrder: 0 },
  { id: 'rice-noodle-wide', name: 'เส้นใหญ่', group: 'carb', sortOrder: 1 },
  { id: 'rice-noodle-thin', name: 'เส้นเล็ก', group: 'carb', sortOrder: 2 },
  { id: 'glass-noodle', name: 'วุ้นเส้น', group: 'carb', sortOrder: 3 },
  { id: 'instant-noodle', name: 'บะหมี่กึ่งสำเร็จรูป', group: 'carb', sortOrder: 4 },
  { id: 'sticky-rice', name: 'ข้าวเหนียว', group: 'carb', sortOrder: 5 },
  { id: 'potato', name: 'มันฝรั่ง', group: 'carb', sortOrder: 6 },
];

export const seedRecipes: Recipe[] = [
  {
    id: 'pad-kra-pao-gai',
    name: 'ผัดกะเพราไก่',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['chicken', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซอสปรุงรส', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมกับพริกให้แหลก ตั้งกระทะใส่น้ำมันจนร้อน ผัดจนหอม',
      'ใส่ไก่สับลงผัดจนสุก ยกไฟแรงตลอด',
      'ปรุงด้วยน้ำมันหอย ซอสปรุงรส น้ำปลา น้ำตาล ผัดให้เข้ากัน',
      'ใส่ใบกะเพรา ผัดเร็วๆ ให้ใบสลด ปิดไฟ ตักราดข้าว โปะไข่ดาว',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-moo',
    name: 'ผัดกะเพราหมูสับ',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['pork-minced', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมพริกให้แหลก ผัดกับน้ำมันจนหอม',
      'ใส่หมูสับ ผัดจนสุกด้วยไฟแรง',
      'ปรุงรสด้วยน้ำมันหอย ซีอิ๊ว น้ำปลา น้ำตาล',
      'ใส่ใบกะเพรา ผัดให้สลด ตักเสิร์ฟพร้อมข้าวสวย',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-pad-moo',
    name: 'ข้าวผัดหมู',
    template: 'ข้าวผัด',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'pork', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียมกับน้ำมันจนหอม ใส่หมูผัดจนสุก',
      'ตอกไข่ลงคนให้สุก แล้วใส่ข้าวสวยลงผัด',
      'ปรุงด้วยซีอิ๊ว น้ำปลา น้ำตาล ผัดให้ข้าวร่วน',
      'ใส่ต้นหอมซอย คลุกเบาๆ ตักเสิร์ฟกับมะนาวและแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-pad-goong',
    name: 'ข้าวผัดกุ้ง',
    template: 'ข้าวผัด',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'shrimp', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียมจนหอม ใส่กุ้งผัดพอเปลี่ยนสี ตักพักไว้',
      'ตอกไข่ลงผัด ใส่ข้าวสวยผัดให้ร่วน',
      'ปรุงรส ใส่กุ้งกลับลงไป ผัดรวมกัน',
      'โรยต้นหอม ตักเสิร์ฟพร้อมมะนาว',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gai-pad-kratiam',
    name: 'ไก่ผัดกระเทียมพริกไทย',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['chicken', 'garlic'],
    requiredIngredientIds: ['garlic'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'สับกระเทียมให้ละเอียด หมักไก่กับกระเทียม ซีอิ๊ว พริกไทย 5 นาที',
      'ตั้งกระทะใส่น้ำมัน ผัดไก่ที่หมักจนสุกและหอมกระเทียม',
      'ปรุงด้วยน้ำมันหอย น้ำตาล ผัดให้เคลือบทั่ว',
      'ตักราดข้าว โรยกระเทียมเจียว เสิร์ฟกับแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'moo-pad-kratiam',
    name: 'หมูผัดกระเทียม',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['pork', 'garlic'],
    requiredIngredientIds: ['garlic'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หมักหมูกับกระเทียมสับ ซีอิ๊ว พริกไทย 5 นาที',
      'ผัดกับน้ำมันร้อนจนสุกและหอม',
      'ปรุงด้วยน้ำมันหอย น้ำตาล ผัดให้เข้ากัน',
      'ตักราดข้าว โรยพริกไทย เสิร์ฟ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-pak-boong',
    name: 'ผัดผักบุ้งไฟแดง',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 6,
    servings: 1,
    coreIngredientIds: ['morning-glory', 'garlic', 'chili'],
    requiredIngredientIds: ['morning-glory'],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'เต้าเจี้ยว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมกับพริก ตั้งกระทะให้ร้อนจัด',
      'ใส่กระเทียมพริกลงผัดให้หอม ใส่ผักบุ้ง',
      'ปรุงด้วยเต้าเจี้ยว น้ำมันหอย น้ำปลา น้ำตาล ผัดเร็วๆ ด้วยไฟแรง',
      'ผัดแค่พอผักสลด ยังเขียวกรอบ ตักเสิร์ฟทันที',
    ],
    tags: ['มังสวิรัติได้', 'เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khai-jiao',
    name: 'ไข่เจียวหมูสับ',
    template: 'ไข่',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 5,
    servings: 1,
    coreIngredientIds: ['egg', 'pork-minced'],
    requiredIngredientIds: ['egg'],
    proteinIngredientIds: ['egg', 'pork-minced'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '3 ชต.' },
    ],
    steps: [
      'ตอกไข่ใส่ชาม ใส่หมูสับ ปรุงน้ำปลา ตีให้ขึ้นฟู',
      'ตั้งน้ำมันให้ร้อนจัด เทไข่ลงกลางกระทะ',
      'พอขอบฟูกรอบ พลิกกลับด้าน ทอดให้เหลืองทั้งสองด้าน',
      'ตักขึ้นสะเด็ดน้ำมัน ราดข้าวสวยร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tom-yum-goong',
    name: 'ต้มยำกุ้งน้ำใส',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: [
      'shrimp',
      'lemongrass',
      'galangal',
      'kaffir-lime-leaf',
      'chili',
      'mushroom',
      'tomato',
    ],
    requiredIngredientIds: ['shrimp'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำพริกเผา', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'ต้มน้ำ ใส่ตะไคร้ทุบ ข่า ใบมะกรูดฉีก ต้มให้หอม',
      'ใส่เห็ดและมะเขือเทศ ต้มให้เดือด',
      'ใส่กุ้งและพริกทุบ ต้มจนกุ้งสุก ปิดไฟ',
      'ปรุงด้วยน้ำปลา น้ำตาล น้ำพริกเผา บีบมะนาว ชิมให้เปรี้ยวนำ',
    ],
    tags: ['เผ็ด', 'เปรี้ยว'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-prik-gaeng-moo',
    name: 'หมูผัดพริกแกง',
    template: 'ผัดพริกแกง',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['pork', 'curry-paste', 'yardlong-bean', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ตั้งน้ำมัน ผัดพริกแกงเผ็ดจนหอมและแตกมัน',
      'ใส่หมูลงผัดจนสุก',
      'ใส่ถั่วฝักยาวหั่นท่อน ผัดพอสุก ปรุงด้วยน้ำมันหอย น้ำปลา น้ำตาล',
      'ใส่ใบมะกรูดฉีก ผัดให้หอม ตักราดข้าว',
    ],
    tags: ['เผ็ด', 'เผ็ดมาก'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-goong',
    name: 'ผัดกะเพรากุ้ง',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['shrimp', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซอสปรุงรส', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมกับพริกให้แหลก ผัดกับน้ำมันจนหอม',
      'ใส่กุ้งลงผัดไฟแรง พอเปลี่ยนสี',
      'ปรุงด้วยน้ำมันหอย ซอสปรุงรส น้ำปลา น้ำตาล',
      'ใส่ใบกะเพรา ผัดเร็วๆ ให้ใบสลด ตักราดข้าว',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-neua',
    name: 'ผัดกะเพราเนื้อ',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['beef', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['beef'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมพริก ผัดกับน้ำมันจนหอม',
      'ใส่เนื้อสับหรือเนื้อหั่นบาง ผัดไฟแรงพอสุก อย่าผัดนานเนื้อจะเหนียว',
      'ปรุงรสด้วยน้ำมันหอย ซีอิ๊ว น้ำปลา น้ำตาล',
      'ใส่ใบกะเพรา ผัดให้สลด ตักราดข้าว โปะไข่ดาว',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-pad-gai',
    name: 'ข้าวผัดไก่',
    template: 'ข้าวผัด',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'chicken', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียมจนหอม ใส่ไก่หั่นชิ้นเล็กผัดจนสุก',
      'ตอกไข่ลงคนให้สุก ใส่ข้าวสวยลงผัด',
      'ปรุงด้วยซีอิ๊ว น้ำปลา น้ำตาล ผัดให้ข้าวร่วน',
      'โรยต้นหอมและพริกไทย เสิร์ฟกับมะนาวและแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-see-ew-moo',
    name: 'ผัดซีอิ๊วหมู',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 15,
    servings: 1,
    coreIngredientIds: ['rice-noodle-wide', 'pork', 'chinese-kale', 'egg', 'garlic'],
    requiredIngredientIds: ['rice-noodle-wide'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วดำ', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'คลุกเส้นใหญ่กับซีอิ๊วดำให้ทั่ว พักไว้',
      'เจียวกระเทียม ใส่หมูผัดจนสุก ตอกไข่ลงคนให้พอสุก',
      'ใส่เส้นลงผัดไฟแรงให้เส้นหอมไหม้นิดๆ ปรุงด้วยซีอิ๊วขาว น้ำมันหอย น้ำตาล',
      'ใส่คะน้าหั่นท่อน ผัดพอสลด ตักเสิร์ฟโรยพริกไทย',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'rad-na-moo',
    name: 'ราดหน้าหมู',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 20,
    servings: 1,
    coreIngredientIds: ['rice-noodle-wide', 'pork', 'chinese-kale', 'garlic'],
    requiredIngredientIds: ['rice-noodle-wide'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'เต้าเจี้ยว', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'ซีอิ๊วดำ', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'แป้งมันละลายน้ำ', amount: '2 ชต.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'คลุกเส้นใหญ่กับซีอิ๊วดำ นำไปผัดไฟแรงให้หอม ตักพักใส่จาน',
      'เจียวกระเทียม ใส่หมูผัดพอสุก เติมน้ำเปล่า 1 ถ้วย',
      'ปรุงด้วยเต้าเจี้ยว ซีอิ๊ว น้ำตาล ใส่คะน้า พอเดือดเติมแป้งมันให้ข้น',
      'ราดลงบนเส้น เสิร์ฟกับพริกน้ำส้มและพริกไทย',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-thai-goong',
    name: 'ผัดไทยกุ้ง',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 3,
    cookTime: 20,
    servings: 1,
    coreIngredientIds: ['rice-noodle-thin', 'shrimp', 'egg', 'bean-sprout', 'spring-onion'],
    requiredIngredientIds: ['rice-noodle-thin'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำตาลปี๊บ', amount: '1.5 ชต.' },
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำมะขามเปียก', amount: '2 ชต.' },
      { name: 'ถั่วลิสงคั่วป่น', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '3 ชต.' },
    ],
    steps: [
      'แช่เส้นเล็กในน้ำอุ่นจนนิ่ม เคี่ยวน้ำตาลปี๊บ น้ำปลา น้ำมะขามเป็นน้ำปรุง',
      'ผัดกุ้งพอสุก ตักพัก ตอกไข่ลงผัดพอสุก',
      'ใส่เส้น ราดน้ำปรุง ผัดให้เส้นนุ่มและแห้ง ใส่กุ้งกลับลงไป',
      'ใส่ถั่วงอกและต้นหอม ผัดเร็วๆ โรยถั่วป่น เสิร์ฟกับมะนาว',
    ],
    tags: ['ไม่เผ็ด', 'เปรี้ยวหวาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'guay-tiew-kua-gai',
    name: 'ก๋วยเตี๋ยวคั่วไก่',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 15,
    servings: 1,
    coreIngredientIds: ['rice-noodle-wide', 'chicken', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['rice-noodle-wide'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'ซีอิ๊วดำ', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียม ใส่ไก่หั่นชิ้นผัดจนสุก',
      'ใส่เส้นใหญ่ ปรุงด้วยซีอิ๊วขาว ซีอิ๊วดำ น้ำตาล',
      'คั่วเส้นบนไฟกลางให้หอมเกรียมนิดๆ ดันเส้นไปข้างกระทะ ตอกไข่ลงคั่วให้ติดเส้น',
      'โรยต้นหอม เสิร์ฟบนใบผักกาดหอม จิ้มพริกน้ำส้ม',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tom-kha-gai',
    name: 'ต้มข่าไก่',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['chicken', 'galangal', 'lemongrass', 'kaffir-lime-leaf', 'mushroom'],
    requiredIngredientIds: ['chicken', 'galangal'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'กะทิ', amount: '1 ถ้วย' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะนาว', amount: '2 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'ต้มกะทิผสมน้ำเปล่า ใส่ข่าหั่นแว่น ตะไคร้ทุบ ใบมะกรูด',
      'พอเดือดใส่ไก่หั่นชิ้น ต้มไฟกลางจนสุก',
      'ใส่เห็ด ปรุงด้วยน้ำปลา น้ำตาล พอเดือดปิดไฟ',
      'บีบมะนาว ชิมให้กลมกล่อมเปรี้ยวมันเค็ม โรยผักชี',
    ],
    tags: ['ไม่เผ็ด', 'ซดคล่อง'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gaeng-kiew-wan-gai',
    name: 'แกงเขียวหวานไก่',
    template: 'แกงกะทิ',
    category: 'ต้ม/แกง',
    difficulty: 3,
    cookTime: 25,
    servings: 2,
    coreIngredientIds: ['chicken', 'curry-paste', 'thai-eggplant', 'thai-basil', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'กะทิ', amount: '2 ถ้วย' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '1 ชต.' },
    ],
    steps: [
      'ผัดพริกแกงเขียวหวานกับหัวกะทิจนหอมแตกมัน',
      'ใส่ไก่ลงผัดให้เข้าเครื่อง เติมกะทิที่เหลือ ต้มจนไก่สุก',
      'ใส่มะเขือเปราะผ่าซีก ปรุงด้วยน้ำปลา น้ำตาลปี๊บ',
      'พอมะเขือนุ่ม ใส่ใบโหระพาและใบมะกรูดฉีก ปิดไฟ เสิร์ฟกับข้าวสวย',
    ],
    tags: ['เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-pak-ruam',
    name: 'ผัดผักรวมมิตร',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 8,
    servings: 2,
    coreIngredientIds: ['cabbage', 'carrot', 'baby-corn', 'mushroom', 'garlic'],
    requiredIngredientIds: [],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นผักทุกอย่างเป็นชิ้นพอคำ แครอทหั่นบางจะสุกไว',
      'เจียวกระเทียมจนหอม ใส่แครอทและข้าวโพดอ่อนผัดก่อน',
      'ใส่กะหล่ำปลีและเห็ด ผัดไฟแรง ปรุงด้วยน้ำมันหอย ซีอิ๊ว น้ำตาล',
      'เติมน้ำเล็กน้อยให้ผักฉ่ำ ผัดพอผักสลดแต่ยังกรอบ ตักเสิร์ฟ',
    ],
    tags: ['มังสวิรัติได้', 'ไม่เผ็ด', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kana-moo',
    name: 'ผัดคะน้าหมู',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 8,
    servings: 1,
    coreIngredientIds: ['chinese-kale', 'pork', 'garlic', 'chili'],
    requiredIngredientIds: ['chinese-kale'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นคะน้าเฉียงๆ แยกก้านกับใบ ทุบกระเทียมพริก',
      'เจียวกระเทียมพริกจนหอม ใส่หมูผัดพอสุก',
      'ใส่ก้านคะน้าก่อน ตามด้วยใบ ผัดไฟแรง',
      'ปรุงด้วยน้ำมันหอย ซีอิ๊ว น้ำตาล ผัดพอสลด ตักเสิร์ฟ',
    ],
    tags: ['เผ็ดน้อย', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tom-jued-taohu',
    name: 'ต้มจืดเต้าหู้หมูสับ',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 1,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['tofu', 'pork-minced', 'napa-cabbage', 'spring-onion', 'garlic'],
    requiredIngredientIds: ['tofu'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'กระเทียมเจียว', amount: '1 ชช.' },
    ],
    steps: [
      'หมักหมูสับกับซีอิ๊วและพริกไทย ปั้นเป็นก้อนเล็กๆ',
      'ต้มน้ำให้เดือด ใส่หมูสับลงต้มจนสุกลอย',
      'ใส่เต้าหู้หั่นชิ้นและผักกาดขาว ต้มต่อจนผักนุ่ม',
      'ปรุงด้วยน้ำปลา โรยต้นหอมและกระเทียมเจียว',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ซดคล่อง'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gai-pad-khing',
    name: 'ไก่ผัดขิง',
    template: 'ผัดขิง',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['chicken', 'ginger', 'mushroom', 'onion', 'spring-onion'],
    requiredIngredientIds: ['ginger'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'เต้าเจี้ยว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ซอยขิงเป็นเส้น หั่นหอมใหญ่และเห็ดเป็นชิ้น',
      'ผัดไก่กับน้ำมันพอสุก ใส่ขิงและหอมใหญ่ผัดให้หอม',
      'ใส่เห็ด ปรุงด้วยเต้าเจี้ยว น้ำมันหอย ซีอิ๊ว น้ำตาล',
      'เติมน้ำนิดหน่อย ผัดให้เข้ากัน โรยต้นหอม ตักราดข้าว',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pla-muek-pad-prik-pao',
    name: 'ปลาหมึกผัดพริกเผา',
    template: 'ผัดพริกเผา',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['squid', 'onion', 'spring-onion', 'chili'],
    requiredIngredientIds: ['squid'],
    proteinIngredientIds: ['squid'],
    seasonings: [
      { name: 'น้ำพริกเผา', amount: '1.5 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นปลาหมึกเป็นชิ้น บั้งลายให้สวย ลวกน้ำเดือดเร็วๆ ตักพัก',
      'ผัดหอมใหญ่กับน้ำมันจนใส ใส่น้ำพริกเผาผัดให้หอม',
      'ใส่ปลาหมึก ผัดไฟแรงเร็วๆ ปรุงด้วยน้ำมันหอย น้ำปลา น้ำตาล',
      'ใส่พริกและต้นหอมท่อน ผัดพอเข้ากัน อย่าผัดนานปลาหมึกจะเหนียว',
    ],
    tags: ['เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'goong-ob-woonsen',
    name: 'กุ้งอบวุ้นเส้น',
    template: 'อบ',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['shrimp', 'glass-noodle', 'ginger', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['shrimp', 'glass-noodle'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำมันงา', amount: '1 ชช.' },
      { name: 'พริกไทยดำ', amount: '1 ชช.' },
      { name: 'น้ำซุป', amount: '1/2 ถ้วย' },
    ],
    steps: [
      'แช่วุ้นเส้นให้นิ่ม คลุกกับซีอิ๊ว น้ำมันหอย น้ำมันงา',
      'เรียงขิงซอย กระเทียมทุบ พริกไทยดำที่ก้นหม้อ',
      'วางกุ้งและวุ้นเส้นลงไป เติมน้ำซุป ปิดฝา',
      'อบไฟกลาง 10 นาทีจนวุ้นเส้นสุกใส โรยต้นหอม เสิร์ฟร้อนๆ',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pla-nueng-manao',
    name: 'ปลานึ่งมะนาว',
    template: 'นึ่ง',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['fish', 'garlic', 'chili', 'lemongrass'],
    requiredIngredientIds: ['fish'],
    proteinIngredientIds: ['fish'],
    seasonings: [
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'น้ำซุป', amount: '3 ชต.' },
    ],
    steps: [
      'บั้งปลา ยัดตะไคร้ทุบในท้องปลา นึ่งน้ำเดือดจัด 12–15 นาทีจนสุก',
      'โขลกกระเทียมพริกหยาบๆ ผสมน้ำมะนาว น้ำปลา น้ำตาล น้ำซุป',
      'ชิมน้ำยำให้เปรี้ยวนำเผ็ดตาม',
      'ราดน้ำยำบนปลาร้อนๆ โรยผักชี เสิร์ฟทันที',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'neua-pad-namman-hoi',
    name: 'เนื้อผัดน้ำมันหอย',
    template: 'ผัดน้ำมันหอย',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['beef', 'onion', 'mushroom', 'spring-onion', 'garlic'],
    requiredIngredientIds: ['beef'],
    proteinIngredientIds: ['beef'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1.5 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นเนื้อบางๆ ขวางเส้น หมักซีอิ๊วพริกไทย 10 นาที',
      'เจียวกระเทียม ใส่เนื้อผัดไฟแรงพอสุกนอกนุ่มใน',
      'ใส่หอมใหญ่และเห็ด ปรุงด้วยน้ำมันหอย น้ำตาล',
      'ใส่ต้นหอมท่อน ผัดพอเข้ากัน ตักราดข้าว',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'goong-pad-pong-karee',
    name: 'กุ้งผัดผงกะหรี่',
    template: 'ผัดผงกะหรี่',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['shrimp', 'egg', 'onion', 'spring-onion'],
    requiredIngredientIds: ['shrimp'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'ผงกะหรี่', amount: '1 ชต.' },
      { name: 'น้ำพริกเผา', amount: '1 ชต.' },
      { name: 'นมข้นจืด', amount: '1/4 ถ้วย' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ผัดกุ้งพอเปลี่ยนสี ตักพักไว้',
      'ผัดหอมใหญ่จนใส ใส่ผงกะหรี่และน้ำพริกเผา ผัดให้หอม',
      'ตีไข่กับนมข้นจืด เทลงกระทะ คนเบาๆ ให้ไข่เป็นครีมข้น',
      'ใส่กุ้งกลับลงไป ปรุงด้วยน้ำมันหอย โรยต้นหอม ตักราดข้าว',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'suki-nam-moo',
    name: 'สุกี้น้ำหมู',
    template: 'ต้ม',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 15,
    servings: 1,
    coreIngredientIds: ['glass-noodle', 'pork', 'egg', 'napa-cabbage', 'garlic'],
    requiredIngredientIds: ['glass-noodle'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำจิ้มสุกี้', amount: '3 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'กระเทียมเจียว', amount: '1 ชช.' },
    ],
    steps: [
      'แช่วุ้นเส้นให้นิ่ม หมักหมูกับซีอิ๊วเล็กน้อย',
      'ต้มน้ำซุปให้เดือด ใส่หมูลงลวกจนสุก',
      'ใส่ผักกาดขาวและวุ้นเส้น พอเดือดตอกไข่ลงคนเบาๆ',
      'ตักใส่ชาม โรยกระเทียมเจียว เสิร์ฟกับน้ำจิ้มสุกี้',
    ],
    tags: ['ไม่เผ็ด', 'ซดคล่อง', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'yum-woonsen',
    name: 'ยำวุ้นเส้น',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['glass-noodle', 'pork-minced', 'shrimp', 'tomato', 'onion', 'chili'],
    requiredIngredientIds: ['glass-noodle'],
    proteinIngredientIds: ['pork-minced', 'shrimp'],
    seasonings: [
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'ลวกวุ้นเส้น หมูสับ และกุ้งให้สุก สะเด็ดน้ำ',
      'ผสมน้ำปลา น้ำมะนาว น้ำตาล พริกซอย เป็นน้ำยำ',
      'คลุกวุ้นเส้น หมูสับ กุ้ง มะเขือเทศ หอมใหญ่ซอยกับน้ำยำ',
      'ชิมรสให้เปรี้ยวนำ โรยผักชีและต้นหอม เสิร์ฟทันที',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'larb-moo',
    name: 'ลาบหมู',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['pork-minced', 'shallot', 'spring-onion', 'chili'],
    requiredIngredientIds: ['pork-minced'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'ข้าวคั่ว', amount: '1 ชต.' },
      { name: 'พริกป่น', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำมะนาว', amount: '2 ชต.' },
    ],
    steps: [
      'รวนหมูสับกับน้ำเล็กน้อยจนสุก ปิดไฟ',
      'ปรุงด้วยน้ำปลา น้ำมะนาว พริกป่น ข้าวคั่ว',
      'ใส่หอมแดงซอย ต้นหอมซอย พริกซอย คลุกให้เข้ากัน',
      'ชิมให้เปรี้ยวเค็มเผ็ดสมดุล เสิร์ฟกับผักสดและข้าวเหนียว',
    ],
    tags: ['เผ็ด', 'อีสาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'kai-palo',
    name: 'ไข่พะโล้',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 45,
    servings: 4,
    coreIngredientIds: ['egg', 'pork', 'tofu', 'garlic'],
    requiredIngredientIds: ['egg'],
    proteinIngredientIds: ['egg', 'pork'],
    seasonings: [
      { name: 'ผงพะโล้', amount: '1 ชต.' },
      { name: 'ซีอิ๊วดำ', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '2 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '2 ชต.' },
      { name: 'น้ำมันพืช', amount: '1 ชต.' },
    ],
    steps: [
      'ต้มไข่ให้สุก ปอกเปลือก เจียวกระเทียมกับน้ำตาลปี๊บจนเป็นคาราเมล',
      'ใส่หมูสามชั้นหั่นชิ้นลงผัดให้เคลือบ ใส่ผงพะโล้ ซีอิ๊ว',
      'เติมน้ำท่วม ใส่ไข่ต้มและเต้าหู้ทอด',
      'เคี่ยวไฟอ่อน 30 นาทีให้น้ำงวดและสีสวย เสิร์ฟกับข้าวสวย',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'mama-pad-kai',
    name: 'มาม่าผัดไข่',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['instant-noodle', 'egg', 'pork-minced', 'cabbage'],
    requiredIngredientIds: ['instant-noodle'],
    proteinIngredientIds: ['egg', 'pork-minced'],
    seasonings: [
      { name: 'เครื่องปรุงมาม่า', amount: '1/2 ซอง' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ลวกมาม่าพอนิ่ม (อย่าเปื่อย) สะเด็ดน้ำ',
      'ผัดหมูสับจนสุก ตอกไข่ลงคนให้พอสุก',
      'ใส่กะหล่ำปลีหั่น ผัดพอสลด ใส่เส้นมาม่า',
      'ปรุงด้วยเครื่องปรุงมาม่า ซีอิ๊ว น้ำมันหอย ผัดไฟแรงให้เข้ากัน',
    ],
    tags: ['จานด่วน', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'som-tam-thai',
    name: 'ส้มตำไทย',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['green-papaya', 'tomato', 'yardlong-bean', 'chili', 'garlic'],
    requiredIngredientIds: ['green-papaya'],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1.5 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'กุ้งแห้ง', amount: '1 ชต.' },
      { name: 'ถั่วลิสงคั่ว', amount: '2 ชต.' },
    ],
    steps: [
      'สับมะละกอดิบเป็นเส้น แช่น้ำเย็นให้กรอบ',
      'โขลกกระเทียมพริกพอแหลก ใส่ถั่วฝักยาวหั่นท่อน ตำเบาๆ',
      'ปรุงด้วยน้ำปลา น้ำตาลปี๊บ น้ำมะนาว ใส่มะเขือเทศผ่าซีก',
      'ใส่เส้นมะละกอ กุ้งแห้ง คลุกตำให้เข้ากัน โรยถั่วลิสง เสิร์ฟกับข้าวเหนียว',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'อีสาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-moo-krob',
    name: 'ผัดกะเพราหมูกรอบ',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['crispy-pork', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['crispy-pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วดำ', amount: '1/2 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '1 ชต.' },
    ],
    steps: [
      'หั่นหมูกรอบเป็นชิ้นพอคำ โขลกกระเทียมพริก',
      'ผัดกระเทียมพริกกับน้ำมันจนหอม ใส่หมูกรอบผัดเร็วๆ',
      'ปรุงด้วยน้ำมันหอย ซีอิ๊วดำ น้ำปลา น้ำตาล อย่าผัดนานหมูจะหายกรอบ',
      'ใส่ใบกะเพรา ผัดให้สลด ตักราดข้าว โปะไข่ดาว',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'kana-moo-krob',
    name: 'คะน้าหมูกรอบ',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 8,
    servings: 1,
    coreIngredientIds: ['chinese-kale', 'crispy-pork', 'garlic', 'chili'],
    requiredIngredientIds: ['chinese-kale'],
    proteinIngredientIds: ['crispy-pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นคะน้าเฉียง หั่นหมูกรอบชิ้นพอคำ',
      'เจียวกระเทียมพริกจนหอม ใส่ก้านคะน้าผัดก่อน',
      'ใส่ใบคะน้าและหมูกรอบ ผัดไฟแรงเร็วๆ',
      'ปรุงด้วยน้ำมันหอย ซีอิ๊ว น้ำตาล ผัดพอสลด ตักเสิร์ฟ',
    ],
    tags: ['เผ็ดน้อย', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-taohu',
    name: 'ผัดกะเพราเต้าหู้',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['tofu', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['tofu'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอยเจ', amount: '1 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นเต้าหู้เป็นลูกเต๋า ทอดพอเหลืองกรอบนอก ตักพัก',
      'ผัดกระเทียมพริกโขลกกับน้ำมันจนหอม',
      'ใส่เต้าหู้ทอด ปรุงด้วยซีอิ๊ว น้ำมันหอยเจ น้ำตาล ผัดเบามือ',
      'ใส่ใบกะเพรา ผัดให้สลด ตักราดข้าว',
    ],
    tags: ['เผ็ด', 'มังสวิรัติได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'fak-tong-pad-kai',
    name: 'ฟักทองผัดไข่',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 12,
    servings: 2,
    coreIngredientIds: ['pumpkin', 'egg', 'garlic'],
    requiredIngredientIds: ['pumpkin'],
    proteinIngredientIds: ['egg'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นฟักทองชิ้นบางพอคำ เจียวกระเทียมจนหอม',
      'ใส่ฟักทองผัด เติมน้ำเล็กน้อย ปิดฝาให้ฟักทองนุ่ม',
      'ปรุงด้วยน้ำมันหอย ซีอิ๊ว น้ำตาล',
      'ตอกไข่ลงไป คนให้ไข่เคลือบฟักทอง ผัดจนไข่สุก ตักเสิร์ฟ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'buab-pad-kai',
    name: 'บวบผัดไข่',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 8,
    servings: 1,
    coreIngredientIds: ['sponge-gourd', 'egg', 'garlic'],
    requiredIngredientIds: ['sponge-gourd'],
    proteinIngredientIds: ['egg'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ปอกเปลือกบวบ หั่นแฉลบเป็นชิ้นพอคำ',
      'เจียวกระเทียมจนหอม ใส่บวบผัดจนเริ่มนุ่ม',
      'ปรุงด้วยน้ำมันหอย ซีอิ๊ว',
      'ตอกไข่ลงคนให้เข้ากัน ผัดจนไข่สุก ตักเสิร์ฟ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kwang-tung',
    name: 'ผัดกวางตุ้งน้ำมันหอย',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 6,
    servings: 1,
    coreIngredientIds: ['choy-sum', 'garlic'],
    requiredIngredientIds: ['choy-sum'],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1.5 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นกวางตุ้งท่อนยาว แยกก้านกับใบ',
      'เจียวกระเทียมจนหอม ใส่ก้านกวางตุ้งผัดก่อน',
      'ใส่ใบ ปรุงด้วยน้ำมันหอย ซีอิ๊ว น้ำตาล',
      'ผัดไฟแรงพอสลด ตักเสิร์ฟทันที',
    ],
    tags: ['มังสวิรัติได้', 'ไม่เผ็ด', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'panang-moo',
    name: 'พะแนงหมู',
    template: 'แกงกะทิ',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['pork', 'curry-paste', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'กะทิ', amount: '1.5 ถ้วย' },
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '1 ชต.' },
    ],
    steps: [
      'ผัดพริกแกงพะแนงกับหัวกะทิจนหอมแตกมัน',
      'ใส่หมูหั่นบางลงผัดให้เข้าเครื่อง',
      'เติมกะทิ เคี่ยวไฟอ่อนให้น้ำแกงข้น ปรุงด้วยน้ำปลา น้ำตาลปี๊บ',
      'โรยใบมะกรูดซอย ราดหัวกะทิ เสิร์ฟกับข้าวสวย',
    ],
    tags: ['เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'chu-chi-pla',
    name: 'ฉู่ฉี่ปลาทอด',
    template: 'แกงกะทิ',
    category: 'ต้ม/แกง',
    difficulty: 3,
    cookTime: 25,
    servings: 2,
    coreIngredientIds: ['fish', 'curry-paste', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['fish', 'curry-paste'],
    proteinIngredientIds: ['fish'],
    seasonings: [
      { name: 'กะทิ', amount: '1 ถ้วย' },
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '3 ชต.' },
    ],
    steps: [
      'ทอดปลาให้เหลืองกรอบ พักไว้',
      'ผัดพริกแกงเผ็ดกับหัวกะทิจนแตกมัน เติมกะทิที่เหลือ',
      'ปรุงด้วยน้ำปลา น้ำตาลปี๊บ เคี่ยวให้ข้น',
      'ราดน้ำฉู่ฉี่บนปลาทอด โรยใบมะกรูดซอยและพริกชี้ฟ้า',
    ],
    tags: ['เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gaeng-som-goong',
    name: 'แกงส้มกุ้งผักรวม',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['shrimp', 'curry-paste', 'yardlong-bean', 'cabbage'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำมะขามเปียก', amount: '3 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
    ],
    steps: [
      'ละลายพริกแกงส้มในน้ำเดือด',
      'ใส่ถั่วฝักยาวและกะหล่ำปลี ต้มจนผักเริ่มนุ่ม',
      'ปรุงด้วยน้ำมะขามเปียก น้ำปลา น้ำตาลปี๊บ ให้เปรี้ยวนำ',
      'ใส่กุ้ง ต้มพอสุก ปิดไฟ เสิร์ฟร้อนๆ',
    ],
    tags: ['เผ็ด', 'เปรี้ยว'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gai-yang',
    name: 'ไก่ย่าง',
    template: 'ย่าง',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 30,
    servings: 2,
    coreIngredientIds: ['chicken', 'garlic', 'sticky-rice'],
    requiredIngredientIds: ['chicken'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '2 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
      { name: 'พริกไทย', amount: '1 ชช.' },
      { name: 'น้ำจิ้มแจ่ว', amount: 'ตามชอบ' },
    ],
    steps: [
      'หมักไก่กับกระเทียมโขลก ซีอิ๊ว น้ำปลา น้ำตาลปี๊บ พริกไทย อย่างน้อย 1 ชั่วโมง',
      'นึ่งข้าวเหนียวให้สุกนุ่ม',
      'ย่างไก่ไฟกลางค่อนอ่อน พลิกกลับด้านจนสุกเหลืองหอม',
      'สับเสิร์ฟพร้อมข้าวเหนียวและน้ำจิ้มแจ่ว',
    ],
    tags: ['ไม่เผ็ด', 'อีสาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'guay-tiew-moo-nam',
    name: 'ก๋วยเตี๋ยวหมูน้ำใส',
    template: 'ต้ม',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 20,
    servings: 1,
    coreIngredientIds: ['rice-noodle-thin', 'pork', 'bean-sprout', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['rice-noodle-thin'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'กระเทียมเจียว', amount: '1 ชต.' },
    ],
    steps: [
      'ต้มน้ำซุปด้วยกระดูกหมูหรือซุปก้อน ปรุงด้วยซีอิ๊วและน้ำปลา',
      'ลวกหมูหั่นบางในน้ำซุปจนสุก',
      'ลวกเส้นเล็กและถั่วงอก ใส่ชาม',
      'ตักหมูและน้ำซุปราด โรยต้นหอม กระเทียมเจียว พริกไทย',
    ],
    tags: ['ไม่เผ็ด', 'ซดคล่อง'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kee-mao-moo',
    name: 'ผัดขี้เมาหมู',
    template: 'ผัดเส้น',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['rice-noodle-wide', 'pork', 'holy-basil', 'chili', 'garlic', 'yardlong-bean'],
    requiredIngredientIds: ['rice-noodle-wide'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วดำ', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมพริกให้แหลก ผัดกับน้ำมันจนหอม',
      'ใส่หมูผัดจนสุก ใส่ถั่วฝักยาวหั่นท่อน',
      'ใส่เส้นใหญ่ ปรุงด้วยน้ำมันหอย ซีอิ๊วดำ น้ำปลา น้ำตาล ผัดไฟแรง',
      'ใส่ใบกะเพรา ผัดให้หอมฉุน ตักเสิร์ฟ',
    ],
    tags: ['เผ็ดมาก', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-tom-moo',
    name: 'ข้าวต้มหมูสับ',
    template: 'ต้ม',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 15,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'pork-minced', 'ginger', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'กระเทียมเจียว', amount: '1 ชต.' },
    ],
    steps: [
      'ต้มน้ำให้เดือด ปั้นหมูสับปรุงรสเป็นก้อนเล็กใส่ลงไป',
      'ใส่ข้าวสวย ต้มจนข้าวบานนุ่ม',
      'ปรุงด้วยซีอิ๊ว ใส่ขิงซอย',
      'ตักใส่ชาม โรยต้นหอม กระเทียมเจียว พริกไทย เสิร์ฟร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'ซดคล่อง', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'kai-toon',
    name: 'ไข่ตุ๋นหมูสับ',
    template: 'นึ่ง',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['egg', 'pork-minced', 'carrot', 'spring-onion'],
    requiredIngredientIds: ['egg'],
    proteinIngredientIds: ['egg', 'pork-minced'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำซุป', amount: '1 ถ้วย' },
    ],
    steps: [
      'ตีไข่กับน้ำซุปอัตราส่วน 1:1 ปรุงด้วยซีอิ๊ว',
      'ใส่หมูสับและแครอทหั่นเต๋าเล็ก คนให้เข้ากัน',
      'กรองใส่ถ้วย ปิดด้วยฟอยล์ นึ่งไฟอ่อน 15 นาทีจนเซตตัว',
      'โรยต้นหอมซอย เสิร์ฟกับข้าวสวยร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'goong-tod-kratiam',
    name: 'กุ้งทอดกระเทียม',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['shrimp', 'garlic'],
    requiredIngredientIds: ['shrimp', 'garlic'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '3 ชต.' },
    ],
    steps: [
      'หมักกุ้งกับซีอิ๊ว พริกไทย 10 นาที สับกระเทียมหยาบๆ',
      'เจียวกระเทียมครึ่งหนึ่งจนเหลืองกรอบ ตักพัก',
      'ผัดกุ้งกับกระเทียมที่เหลือจนสุกหอม ปรุงด้วยน้ำมันหอย',
      'ตักราดข้าว โรยกระเทียมเจียว เสิร์ฟกับแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pla-tod-kratiam',
    name: 'ปลาทอดกระเทียม',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['fish', 'garlic'],
    requiredIngredientIds: ['fish'],
    proteinIngredientIds: ['fish'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '1 ถ้วย (สำหรับทอด)' },
    ],
    steps: [
      'บั้งปลา คลุกน้ำปลาพริกไทย พักไว้ 15 นาที',
      'ทอดปลาในน้ำมันร้อนจนเหลืองกรอบทั้งสองด้าน ตักพัก',
      'เจียวกระเทียมสับในน้ำมันเดิมจนเหลืองหอม',
      'โรยกระเทียมเจียวบนปลา เสิร์ฟกับข้าวสวยและน้ำจิ้มซีฟู้ด',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'yum-pla-krapong',
    name: 'ยำปลากระป๋อง',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 1,
    cookTime: 10,
    servings: 2,
    coreIngredientIds: ['canned-fish', 'onion', 'tomato', 'chili', 'spring-onion'],
    requiredIngredientIds: ['canned-fish'],
    proteinIngredientIds: ['canned-fish'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'น้ำมะนาว', amount: '2 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
    ],
    steps: [
      'เทปลากระป๋องใส่จาน แบ่งชิ้นพอคำ',
      'ซอยหอมใหญ่ มะเขือเทศ พริก ต้นหอม',
      'ผสมน้ำปลา น้ำมะนาว น้ำตาล ราดลงไป',
      'คลุกเบาๆ ให้เข้ากัน ชิมรสเปรี้ยวนำ เสิร์ฟกับข้าวสวยร้อนๆ',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'ทำง่าย', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'yum-mama',
    name: 'ยำมาม่า',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['instant-noodle', 'pork-minced', 'shrimp', 'tomato', 'onion', 'chili'],
    requiredIngredientIds: ['instant-noodle'],
    proteinIngredientIds: ['pork-minced', 'shrimp'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำมะนาว', amount: '2.5 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'เครื่องปรุงมาม่า', amount: '1/2 ซอง' },
    ],
    steps: [
      'ลวกมาม่าพอนิ่ม สะเด็ดน้ำ ลวกหมูสับและกุ้งให้สุก',
      'ผสมน้ำปลา น้ำมะนาว น้ำตาล เครื่องปรุงมาม่า พริกซอย เป็นน้ำยำ',
      'คลุกเส้น หมูสับ กุ้ง มะเขือเทศ หอมใหญ่ กับน้ำยำ',
      'ชิมรสจัดๆ เปรี้ยวเผ็ดนำ โรยต้นหอมผักชี เสิร์ฟทันที',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-kai-khon-goong',
    name: 'ข้าวไข่ข้นกุ้ง',
    template: 'ไข่',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'egg', 'shrimp', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice', 'egg'],
    proteinIngredientIds: ['egg', 'shrimp'],
    seasonings: [
      { name: 'ซอสปรุงรส', amount: '1 ชช.' },
      { name: 'นมสด', amount: '2 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ผัดกุ้งกับน้ำมันหอยพอสุก ตักพัก',
      'ตีไข่กับนมสดและซอสปรุงรส',
      'เทไข่ลงกระทะไฟอ่อน คนวนช้าๆ ให้ไข่เป็นครีมกึ่งสุก ใส่กุ้ง',
      'เทราดบนข้าวสวยร้อนๆ ทันที โรยต้นหอมซอย',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'moo-manao',
    name: 'หมูมะนาว',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 1,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['pork', 'garlic', 'chili', 'chinese-kale'],
    requiredIngredientIds: ['pork'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'หั่นหมูบางๆ ลวกในน้ำเดือดพอสุก สะเด็ดน้ำ',
      'โขลกกระเทียมพริก ผสมน้ำมะนาว น้ำปลา น้ำตาล เป็นน้ำยำ',
      'จัดหมูวางบนคะน้าซอยฝอย',
      'ราดน้ำยำให้ทั่ว เสิร์ฟทันทีตอนหมูยังอุ่น',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'สุขภาพ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-priew-wan-moo',
    name: 'ผัดเปรี้ยวหวานหมู',
    template: 'ผัดเปรี้ยวหวาน',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['pork', 'onion', 'tomato', 'cucumber', 'carrot'],
    requiredIngredientIds: ['pork'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซอสมะเขือเทศ', amount: '2 ชต.' },
      { name: 'น้ำส้มสายชู', amount: '1 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นผักทุกอย่างเป็นชิ้นพอคำ หั่นหมูบาง',
      'ผัดหมูพอสุก ใส่หอมใหญ่และแครอทผัดก่อน',
      'ปรุงด้วยซอสมะเขือเทศ น้ำส้มสายชู น้ำตาล ซีอิ๊ว',
      'ใส่มะเขือเทศและแตงกวา ผัดพอสลด ตักราดข้าว',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pla-rad-prik',
    name: 'ปลาราดพริก',
    template: 'ทอด',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 25,
    servings: 2,
    coreIngredientIds: ['fish', 'chili', 'garlic', 'shallot'],
    requiredIngredientIds: ['fish'],
    proteinIngredientIds: ['fish'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '2 ชต.' },
      { name: 'น้ำมะขามเปียก', amount: '2 ชต.' },
      { name: 'น้ำมันพืช', amount: '1 ถ้วย (สำหรับทอด)' },
    ],
    steps: [
      'ทอดปลาให้เหลืองกรอบ พักไว้บนจาน',
      'โขลกพริก กระเทียม หอมแดงหยาบๆ ผัดกับน้ำมันจนหอม',
      'ปรุงด้วยน้ำปลา น้ำตาลปี๊บ น้ำมะขาม เคี่ยวให้ข้นเป็นซอสสามรส',
      'ราดซอสบนปลาทอด โรยใบโหระพาทอดกรอบ',
    ],
    tags: ['เผ็ด', 'เปรี้ยวหวาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tom-yum-goong-nam-khon',
    name: 'ต้มยำกุ้งน้ำข้น',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['shrimp', 'lemongrass', 'galangal', 'kaffir-lime-leaf', 'chili', 'mushroom'],
    requiredIngredientIds: ['shrimp'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำพริกเผา', amount: '2 ชต.' },
      { name: 'นมข้นจืด', amount: '1/2 ถ้วย' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
    ],
    steps: [
      'ต้มน้ำกับตะไคร้ ข่า ใบมะกรูด ให้หอม',
      'ใส่เห็ด พอเดือดใส่กุ้ง ต้มจนสุก',
      'ใส่น้ำพริกเผาและนมข้นจืด คนให้น้ำซุปข้นเป็นสีส้ม',
      'ปิดไฟ ปรุงด้วยน้ำปลา น้ำมะนาว พริกทุบ ชิมให้เข้มข้นจัดจ้าน',
    ],
    tags: ['เผ็ด', 'เปรี้ยว'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'kai-look-keuy',
    name: 'ไข่ลูกเขย',
    template: 'ไข่',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['egg', 'shallot'],
    requiredIngredientIds: ['egg'],
    proteinIngredientIds: ['egg'],
    seasonings: [
      { name: 'น้ำตาลปี๊บ', amount: '2 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'น้ำมะขามเปียก', amount: '2 ชต.' },
      { name: 'น้ำมันพืช', amount: '1/2 ถ้วย' },
    ],
    steps: [
      'ต้มไข่ให้สุก ปอกเปลือก ซับให้แห้ง',
      'ทอดไข่ต้มในน้ำมันร้อนจนผิวเหลืองกรอบ ตักพัก',
      'เจียวหอมแดงซอยจนกรอบ ตักพัก เคี่ยวน้ำตาลปี๊บ น้ำปลา น้ำมะขามให้ข้น',
      'ผ่าครึ่งไข่ ราดซอส โรยหอมเจียวและพริกทอด',
    ],
    tags: ['ไม่เผ็ด', 'เปรี้ยวหวาน', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'nam-tok-moo',
    name: 'น้ำตกหมู',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['pork', 'shallot', 'spring-onion'],
    requiredIngredientIds: ['pork'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ข้าวคั่ว', amount: '1 ชต.' },
      { name: 'พริกป่น', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1.5 ชต.' },
      { name: 'น้ำมะนาว', amount: '2 ชต.' },
    ],
    steps: [
      'ย่างหมู (สันคอยิ่งดี) ให้สุกกำลังดี หั่นชิ้นบางพอคำ',
      'คลุกหมูกับน้ำปลา น้ำมะนาว พริกป่น ขณะยังอุ่น',
      'ใส่ข้าวคั่ว หอมแดงซอย ต้นหอมซอย คลุกให้เข้ากัน',
      'ชิมรสแซ่บเปรี้ยวเผ็ด เสิร์ฟกับข้าวเหนียวและผักสด',
    ],
    tags: ['เผ็ด', 'อีสาน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'jok-moo',
    name: 'โจ๊กหมู',
    template: 'ต้ม',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 25,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'pork-minced', 'egg', 'ginger', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'กระเทียมเจียว', amount: '1 ชต.' },
    ],
    steps: [
      'ปั่นหรือบี้ข้าวสวยหยาบๆ ต้มกับน้ำจนเละเนียนเป็นโจ๊ก',
      'ปั้นหมูสับปรุงรสเป็นก้อน ใส่ลงต้มจนสุก',
      'ตอกไข่ลงตรงกลาง ปิดไฟ ปิดฝาให้ไข่เป็นยางมะตูม',
      'โรยขิงซอย ต้นหอม กระเทียมเจียว พริกไทย เสิร์ฟร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'อาหารเช้า', 'เด็กกินได้', 'ซดคล่อง'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'peek-gai-tod-nam-pla',
    name: 'ปีกไก่ทอดน้ำปลา',
    template: 'ทอด',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['chicken', 'garlic'],
    requiredIngredientIds: ['chicken'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'แป้งทอดกรอบ', amount: '3 ชต.' },
      { name: 'น้ำมันพืช', amount: '2 ถ้วย (สำหรับทอด)' },
    ],
    steps: [
      'หมักปีกไก่กับน้ำปลา น้ำตาล กระเทียมโขลก 30 นาที',
      'คลุกแป้งทอดกรอบบางๆ',
      'ทอดน้ำมันร้อนปานกลางจนเหลืองกรอบ สะเด็ดน้ำมัน',
      'เจียวกระเทียมโรยหน้า เสิร์ฟร้อนๆ กับข้าวสวยหรือข้าวเหนียว',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'massaman-gai',
    name: 'มัสมั่นไก่',
    template: 'แกงกะทิ',
    category: 'ต้ม/แกง',
    difficulty: 3,
    cookTime: 45,
    servings: 4,
    coreIngredientIds: ['chicken', 'curry-paste', 'onion', 'potato'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'กะทิ', amount: '2 ถ้วย' },
      { name: 'น้ำตาลปี๊บ', amount: '2 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะขามเปียก', amount: '2 ชต.' },
      { name: 'ถั่วลิสงคั่ว', amount: '1/4 ถ้วย' },
    ],
    steps: [
      'ผัดพริกแกงมัสมั่นกับหัวกะทิจนหอมแตกมัน',
      'ใส่ไก่ (น่องหรือสะโพก) ผัดให้เข้าเครื่อง เติมกะทิ',
      'ใส่มันฝรั่งหั่นชิ้นใหญ่ หอมใหญ่ ถั่วลิสง เคี่ยวไฟอ่อน 30 นาที',
      'ปรุงด้วยน้ำตาลปี๊บ น้ำปลา น้ำมะขาม ให้หวานนำเค็มตาม เสิร์ฟกับข้าว',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gaeng-jued-woonsen',
    name: 'แกงจืดวุ้นเส้นหมูสับ',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 1,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['glass-noodle', 'pork-minced', 'spring-onion', 'garlic'],
    requiredIngredientIds: ['glass-noodle'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'กระเทียมเจียว', amount: '1 ชช.' },
    ],
    steps: [
      'แช่วุ้นเส้นให้นิ่ม หมักหมูสับกับซีอิ๊วพริกไทย ปั้นก้อน',
      'ต้มน้ำเดือด ใส่หมูสับลงต้มจนสุกลอย',
      'ใส่วุ้นเส้น ต้มต่อ 2-3 นาที ปรุงด้วยน้ำปลา',
      'โรยต้นหอมและกระเทียมเจียว เสิร์ฟร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ซดคล่อง'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'kalam-plee-pad-nam-pla',
    name: 'กะหล่ำปลีผัดน้ำปลา',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 6,
    servings: 1,
    coreIngredientIds: ['cabbage', 'garlic'],
    requiredIngredientIds: ['cabbage'],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หั่นกะหล่ำปลีชิ้นใหญ่ ทุบกระเทียมพอแตก',
      'ตั้งกระทะไฟแรง ใส่น้ำมันและกระเทียม',
      'ใส่กะหล่ำปลีผัดเร็วๆ เหยาะน้ำปลารอบกระทะให้หอม',
      'ผัดพอสลดแต่ยังกรอบ ตักเสิร์ฟทันที',
    ],
    tags: ['มังสวิรัติได้', 'ไม่เผ็ด', 'ทำง่าย', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'hoy-lai-pad-prik-pao',
    name: 'หอยลายผัดน้ำพริกเผา',
    template: 'ผัดพริกเผา',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 10,
    servings: 2,
    coreIngredientIds: ['clam', 'thai-basil', 'garlic', 'chili'],
    requiredIngredientIds: ['clam'],
    proteinIngredientIds: ['clam'],
    seasonings: [
      { name: 'น้ำพริกเผา', amount: '2 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ล้างหอยลายให้สะอาด แช่น้ำให้คายทราย',
      'เจียวกระเทียมพริกจนหอม ใส่น้ำพริกเผาผัดให้ละลาย',
      'ใส่หอยลาย ผัดไฟแรง ปิดฝาสักครู่ให้หอยอ้า',
      'ปรุงด้วยน้ำมันหอย น้ำปลา ใส่ใบโหระพา ผัดให้หอม ตักเสิร์ฟ',
    ],
    tags: ['เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'poo-pad-pong-karee',
    name: 'ปูผัดผงกะหรี่',
    template: 'ผัดผงกะหรี่',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['crab-meat', 'egg', 'onion', 'spring-onion'],
    requiredIngredientIds: ['crab-meat'],
    proteinIngredientIds: ['crab-meat'],
    seasonings: [
      { name: 'ผงกะหรี่', amount: '1 ชต.' },
      { name: 'น้ำพริกเผา', amount: '1 ชต.' },
      { name: 'นมข้นจืด', amount: '1/4 ถ้วย' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ผัดหอมใหญ่กับน้ำมันจนใส ใส่ผงกะหรี่และน้ำพริกเผาผัดให้หอม',
      'ตีไข่กับนมข้นจืด เทลงกระทะ คนเบาๆ ให้เป็นครีม',
      'ใส่เนื้อปู คลุกเบามือไม่ให้เนื้อปูแหลก',
      'ปรุงด้วยน้ำมันหอย ใส่ต้นหอมท่อน ตักราดข้าวสวย',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'nam-prik-kapi-pla-too',
    name: 'น้ำพริกกะปิ ปลาทูทอด',
    template: 'น้ำพริก',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 20,
    servings: 2,
    coreIngredientIds: ['mackerel', 'chili', 'garlic', 'shallot', 'yardlong-bean'],
    requiredIngredientIds: ['mackerel'],
    proteinIngredientIds: ['mackerel'],
    seasonings: [
      { name: 'กะปิ', amount: '1 ชต.' },
      { name: 'น้ำมะนาว', amount: '2 ชต.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '1/2 ถ้วย (สำหรับทอด)' },
    ],
    steps: [
      'ทอดปลาทูให้เหลืองกรอบ พักไว้',
      'โขลกกะปิ กระเทียม พริก หอมแดง ให้เข้ากัน',
      'ปรุงด้วยน้ำมะนาว น้ำตาลปี๊บ น้ำปลา ชิมให้สามรสสมดุล',
      'เสิร์ฟน้ำพริกกับปลาทูทอด ผักสดและผักลวก เช่น ถั่วฝักยาว แตงกวา',
    ],
    tags: ['เผ็ด', 'อาหารไทยแท้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tod-man-pla',
    name: 'ทอดมันปลา',
    template: 'ทอด',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 25,
    servings: 2,
    coreIngredientIds: ['fish', 'curry-paste', 'yardlong-bean', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['fish', 'curry-paste'],
    proteinIngredientIds: ['fish'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
      { name: 'น้ำจิ้มอาจาด', amount: 'ตามชอบ' },
      { name: 'น้ำมันพืช', amount: '2 ถ้วย (สำหรับทอด)' },
    ],
    steps: [
      'โขลกหรือปั่นเนื้อปลากับพริกแกงจนเหนียว ปรุงด้วยน้ำปลา น้ำตาล',
      'ใส่ถั่วฝักยาวซอยและใบมะกรูดซอย นวดให้เข้ากัน',
      'ปั้นเป็นแผ่นกลมแบน ทอดน้ำมันร้อนจนเหลืองสุก',
      'สะเด็ดน้ำมัน เสิร์ฟกับน้ำจิ้มอาจาดแตงกวา',
    ],
    tags: ['เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'goong-chae-nam-pla',
    name: 'กุ้งแช่น้ำปลา',
    template: 'ยำ',
    category: 'ยำ/ลาบ',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: ['shrimp', 'garlic', 'chili', 'cabbage'],
    requiredIngredientIds: ['shrimp'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำปลา', amount: '3 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'ใช้กุ้งสดมาก ปอกเปลือกผ่าหลัง ล้างน้ำเย็นจัด',
      'ผสมน้ำปลา น้ำมะนาว น้ำตาล เป็นน้ำจิ้มรสจัด',
      'เรียงกุ้งบนกะหล่ำปลีซอย ราดน้ำจิ้ม',
      'โรยกระเทียมสไลซ์บาง พริกซอย และสะระแหน่ เสิร์ฟเย็นๆ ทันที',
    ],
    tags: ['เผ็ด', 'เปรี้ยว', 'เมนูดิบ'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-cha-talay',
    name: 'ผัดฉ่าทะเล',
    template: 'ผัดฉ่า',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 12,
    servings: 2,
    coreIngredientIds: ['shrimp', 'squid', 'thai-basil', 'chili', 'garlic'],
    requiredIngredientIds: [],
    proteinIngredientIds: ['shrimp', 'squid'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซอสปรุงรส', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมพริกหยาบๆ ลวกกุ้งและปลาหมึกเร็วๆ ตักพัก',
      'ผัดกระเทียมพริกกับน้ำมันไฟแรงจนหอมฉุน',
      'ใส่กุ้งปลาหมึก ปรุงด้วยน้ำมันหอย ซอสปรุงรส น้ำปลา น้ำตาล',
      'ใส่ใบโหระพา (มีกระชายหรือพริกไทยอ่อนยิ่งดี) ผัดเร็วๆ ตักเสิร์ฟ',
    ],
    tags: ['เผ็ดมาก'],
    updatedAt: SEED_UPDATED_AT,
  },
];

export const seedCatalog: Catalog = {
  ingredients: seedIngredients,
  recipes: seedRecipes,
  updatedAt: SEED_UPDATED_AT,
};
