import type { Catalog, Ingredient, Recipe } from './types.ts';

/** timestamp เดียวกันทั้งชุด — ใช้เป็นค่า updatedAt ตั้งต้นของคลัง */
export const SEED_UPDATED_AT = '2026-07-03T00:00:00.000Z';

export const seedIngredients: Ingredient[] = [
  // โปรตีน
  { id: 'chicken', name: 'ไก่', group: 'protein', sortOrder: 0 },
  { id: 'pork', name: 'หมู', group: 'protein', sortOrder: 1 },
  { id: 'pork-minced', name: 'หมูสับ', group: 'protein', sortOrder: 2 },
  { id: 'shrimp', name: 'กุ้ง', group: 'protein', sortOrder: 3 },
  { id: 'egg', name: 'ไข่', group: 'protein', sortOrder: 4 },
  // ผักและสมุนไพร
  { id: 'holy-basil', name: 'ใบกะเพรา', group: 'vegetable', sortOrder: 0 },
  { id: 'garlic', name: 'กระเทียม', group: 'vegetable', sortOrder: 1 },
  { id: 'chili', name: 'พริก', group: 'vegetable', sortOrder: 2 },
  { id: 'morning-glory', name: 'ผักบุ้ง', group: 'vegetable', sortOrder: 3 },
  { id: 'spring-onion', name: 'ต้นหอม', group: 'vegetable', sortOrder: 4 },
  { id: 'yardlong-bean', name: 'ถั่วฝักยาว', group: 'vegetable', sortOrder: 5 },
  { id: 'tomato', name: 'มะเขือเทศ', group: 'vegetable', sortOrder: 6 },
  { id: 'lemongrass', name: 'ตะไคร้', group: 'vegetable', sortOrder: 7 },
  { id: 'galangal', name: 'ข่า', group: 'vegetable', sortOrder: 8 },
  { id: 'kaffir-lime-leaf', name: 'ใบมะกรูด', group: 'vegetable', sortOrder: 9 },
  { id: 'mushroom', name: 'เห็ด', group: 'vegetable', sortOrder: 10 },
  { id: 'curry-paste', name: 'พริกแกง', group: 'vegetable', sortOrder: 11 },
  // คาร์โบไฮเดรต
  { id: 'cooked-rice', name: 'ข้าวสวย', group: 'carb', sortOrder: 0 },
];

export const seedRecipes: Recipe[] = [
  {
    id: 'pad-kra-pao-gai',
    name: 'ผัดกะเพราไก่',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['chicken', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซอสปรุงรส', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมกับพริกให้แหลก ตั้งกระทะใส่น้ำมันจนร้อน ผัดจนหอม',
      'ใส่ไก่สับลงผัดจนสุก ยกไฟแรงตลอด',
      'ปรุงด้วยน้ำมันหอย ซอสปรุงรส น้ำปลา น้ำตาล ผัดให้เข้ากัน',
      'ใส่ใบกะเพรา ผัดเร็วๆ ให้ใบสลด ปิดไฟ ตักราดข้าว โปะไข่ดาว',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-kra-pao-moo',
    name: 'ผัดกะเพราหมูสับ',
    template: 'ผัดกะเพรา',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['pork-minced', 'holy-basil', 'chili', 'garlic'],
    requiredIngredientIds: ['holy-basil'],
    proteinIngredientIds: ['pork-minced'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'ซีอิ๊วขาว', amount: '1 ชช.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมพริกให้แหลก ผัดกับน้ำมันจนหอม',
      'ใส่หมูสับ ผัดจนสุกด้วยไฟแรง',
      'ปรุงรสด้วยน้ำมันหอย ซีอิ๊ว น้ำปลา น้ำตาล',
      'ใส่ใบกะเพรา ผัดให้สลด ตักเสิร์ฟพร้อมข้าวสวย',
    ],
    tags: ['เผ็ด', 'จานด่วน'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-pad-moo',
    name: 'ข้าวผัดหมู',
    template: 'ข้าวผัด',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'pork', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียมกับน้ำมันจนหอม ใส่หมูผัดจนสุก',
      'ตอกไข่ลงคนให้สุก แล้วใส่ข้าวสวยลงผัด',
      'ปรุงด้วยซีอิ๊ว น้ำปลา น้ำตาล ผัดให้ข้าวร่วน',
      'ใส่ต้นหอมซอย คลุกเบาๆ ตักเสิร์ฟกับมะนาวและแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'อิ่มง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khao-pad-goong',
    name: 'ข้าวผัดกุ้ง',
    template: 'ข้าวผัด',
    category: 'อาหารจานเดียว',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['cooked-rice', 'shrimp', 'egg', 'garlic', 'spring-onion'],
    requiredIngredientIds: ['cooked-rice'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'พริกไทย', amount: 'เล็กน้อย' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'เจียวกระเทียมจนหอม ใส่กุ้งผัดพอเปลี่ยนสี ตักพักไว้',
      'ตอกไข่ลงผัด ใส่ข้าวสวยผัดให้ร่วน',
      'ปรุงรส ใส่กุ้งกลับลงไป ผัดรวมกัน',
      'โรยต้นหอม ตักเสิร์ฟพร้อมมะนาว',
    ],
    tags: ['ไม่เผ็ด'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'gai-pad-kratiam',
    name: 'ไก่ผัดกระเทียมพริกไทย',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['chicken', 'garlic'],
    requiredIngredientIds: ['garlic'],
    proteinIngredientIds: ['chicken'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'สับกระเทียมให้ละเอียด หมักไก่กับกระเทียม ซีอิ๊ว พริกไทย 5 นาที',
      'ตั้งกระทะใส่น้ำมัน ผัดไก่ที่หมักจนสุกและหอมกระเทียม',
      'ปรุงด้วยน้ำมันหอย น้ำตาล ผัดให้เคลือบทั่ว',
      'ตักราดข้าว โรยกระเทียมเจียว เสิร์ฟกับแตงกวา',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'moo-pad-kratiam',
    name: 'หมูผัดกระเทียม',
    template: 'ผัดกระเทียม',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 10,
    servings: 1,
    coreIngredientIds: ['pork', 'garlic'],
    requiredIngredientIds: ['garlic'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'ซีอิ๊วขาว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชช.' },
      { name: 'พริกไทย', amount: '1/2 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'หมักหมูกับกระเทียมสับ ซีอิ๊ว พริกไทย 5 นาที',
      'ผัดกับน้ำมันร้อนจนสุกและหอม',
      'ปรุงด้วยน้ำมันหอย น้ำตาล ผัดให้เข้ากัน',
      'ตักราดข้าว โรยพริกไทย เสิร์ฟ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-pak-boong',
    name: 'ผัดผักบุ้งไฟแดง',
    template: 'ผัดผัก',
    category: 'อาหารตามสั่ง',
    difficulty: 1,
    cookTime: 6,
    servings: 1,
    coreIngredientIds: ['morning-glory', 'garlic', 'chili'],
    requiredIngredientIds: ['morning-glory'],
    proteinIngredientIds: [],
    seasonings: [
      { name: 'เต้าเจี้ยว', amount: '1 ชต.' },
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลทราย', amount: '1/2 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'โขลกกระเทียมกับพริก ตั้งกระทะให้ร้อนจัด',
      'ใส่กระเทียมพริกลงผัดให้หอม ใส่ผักบุ้ง',
      'ปรุงด้วยเต้าเจี้ยว น้ำมันหอย น้ำปลา น้ำตาล ผัดเร็วๆ ด้วยไฟแรง',
      'ผัดแค่พอผักสลด ยังเขียวกรอบ ตักเสิร์ฟทันที',
    ],
    tags: ['มังสวิรัติได้', 'เผ็ดน้อย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'khai-jiao',
    name: 'ไข่เจียวหมูสับ',
    template: 'ไข่',
    category: 'อาหารจานเดียว',
    difficulty: 1,
    cookTime: 5,
    servings: 1,
    coreIngredientIds: ['egg', 'pork-minced'],
    requiredIngredientIds: ['egg'],
    proteinIngredientIds: ['egg', 'pork-minced'],
    seasonings: [
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '3 ชต.' },
    ],
    steps: [
      'ตอกไข่ใส่ชาม ใส่หมูสับ ปรุงน้ำปลา ตีให้ขึ้นฟู',
      'ตั้งน้ำมันให้ร้อนจัด เทไข่ลงกลางกระทะ',
      'พอขอบฟูกรอบ พลิกกลับด้าน ทอดให้เหลืองทั้งสองด้าน',
      'ตักขึ้นสะเด็ดน้ำมัน ราดข้าวสวยร้อนๆ',
    ],
    tags: ['ไม่เผ็ด', 'เด็กกินได้', 'ทำง่าย'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'tom-yum-goong',
    name: 'ต้มยำกุ้งน้ำใส',
    template: 'ต้ม',
    category: 'ต้ม/แกง',
    difficulty: 2,
    cookTime: 15,
    servings: 2,
    coreIngredientIds: [
      'shrimp',
      'lemongrass',
      'galangal',
      'kaffir-lime-leaf',
      'chili',
      'mushroom',
      'tomato',
    ],
    requiredIngredientIds: ['shrimp'],
    proteinIngredientIds: ['shrimp'],
    seasonings: [
      { name: 'น้ำพริกเผา', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '2 ชต.' },
      { name: 'น้ำมะนาว', amount: '3 ชต.' },
      { name: 'น้ำตาลทราย', amount: '1 ชช.' },
    ],
    steps: [
      'ต้มน้ำ ใส่ตะไคร้ทุบ ข่า ใบมะกรูดฉีก ต้มให้หอม',
      'ใส่เห็ดและมะเขือเทศ ต้มให้เดือด',
      'ใส่กุ้งและพริกทุบ ต้มจนกุ้งสุก ปิดไฟ',
      'ปรุงด้วยน้ำปลา น้ำตาล น้ำพริกเผา บีบมะนาว ชิมให้เปรี้ยวนำ',
    ],
    tags: ['เผ็ด', 'เปรี้ยว'],
    updatedAt: SEED_UPDATED_AT,
  },
  {
    id: 'pad-prik-gaeng-moo',
    name: 'หมูผัดพริกแกง',
    template: 'ผัดพริกแกง',
    category: 'อาหารตามสั่ง',
    difficulty: 2,
    cookTime: 12,
    servings: 1,
    coreIngredientIds: ['pork', 'curry-paste', 'yardlong-bean', 'kaffir-lime-leaf'],
    requiredIngredientIds: ['curry-paste'],
    proteinIngredientIds: ['pork'],
    seasonings: [
      { name: 'น้ำมันหอย', amount: '1 ชต.' },
      { name: 'น้ำปลา', amount: '1 ชช.' },
      { name: 'น้ำตาลปี๊บ', amount: '1 ชช.' },
      { name: 'น้ำมันพืช', amount: '2 ชต.' },
    ],
    steps: [
      'ตั้งน้ำมัน ผัดพริกแกงเผ็ดจนหอมและแตกมัน',
      'ใส่หมูลงผัดจนสุก',
      'ใส่ถั่วฝักยาวหั่นท่อน ผัดพอสุก ปรุงด้วยน้ำมันหอย น้ำปลา น้ำตาล',
      'ใส่ใบมะกรูดฉีก ผัดให้หอม ตักราดข้าว',
    ],
    tags: ['เผ็ด', 'เผ็ดมาก'],
    updatedAt: SEED_UPDATED_AT,
  },
];

export const seedCatalog: Catalog = {
  ingredients: seedIngredients,
  recipes: seedRecipes,
  updatedAt: SEED_UPDATED_AT,
};
